import TableBodyRow from "../TableBodyRow";

const TableBody = ({
  exchangeRate,
  handleTableDataClick,
  tableDataFrom,
  tableDataTo,
  selectedFrom,
  selectedTo,
  active,
  tableBodyRows,
}) => (
  <tbody>
    <TableBodyRow
      handleTableDataClick={handleTableDataClick}
      exchangeRate={exchangeRate}
      tableDataFrom={tableDataFrom}
      tableDataTo={tableDataTo}
      selectedFrom={selectedFrom}
      selectedTo={selectedTo}
      active={active}
      index={0}
      tableBodyRows={tableBodyRows}
    />
    <TableBodyRow
      handleTableDataClick={handleTableDataClick}
      exchangeRate={exchangeRate}
      tableDataFrom={tableDataFrom}
      tableDataTo={tableDataTo}
      selectedFrom={selectedFrom}
      selectedTo={selectedTo}
      active={active}
      index={1}
      tableBodyRows={tableBodyRows}
    />
    <TableBodyRow
      handleTableDataClick={handleTableDataClick}
      exchangeRate={exchangeRate}
      tableDataFrom={tableDataFrom}
      tableDataTo={tableDataTo}
      selectedFrom={selectedFrom}
      selectedTo={selectedTo}
      active={active}
      index={2}
      tableBodyRows={tableBodyRows}
    />
    <TableBodyRow
      handleTableDataClick={handleTableDataClick}
      exchangeRate={exchangeRate}
      tableDataFrom={tableDataFrom}
      tableDataTo={tableDataTo}
      selectedFrom={selectedFrom}
      selectedTo={selectedTo}
      active={active}
      index={3}
      tableBodyRows={tableBodyRows}
    />
    <TableBodyRow
      handleTableDataClick={handleTableDataClick}
      exchangeRate={exchangeRate}
      tableDataFrom={tableDataFrom}
      tableDataTo={tableDataTo}
      selectedFrom={selectedFrom}
      selectedTo={selectedTo}
      active={active}
      index={4}
      tableBodyRows={tableBodyRows}
    />
  </tbody>
);

export default TableBody;
