import TableBodyRow from "../TableBodyRow";

const TableBody = ({
  exchangeRate,
  changeFormValues,
  selectFrom,
  selectTo,
  selectedFrom,
  selectedTo,
  active,
  tdItems,
  tableBodyRows,
}) => (
  <tbody>
    <TableBodyRow
      changeFormValues={changeFormValues}
      exchangeRate={exchangeRate}
      selectFrom={selectFrom}
      selectTo={selectTo}
      selectedFrom={selectedFrom}
      selectedTo={selectedTo}
      active={active}
      index={0}
      tdItems={tdItems}
      tableBodyRows={tableBodyRows}
    />
    <TableBodyRow
      changeFormValues={changeFormValues}
      exchangeRate={exchangeRate}
      selectFrom={selectFrom}
      selectTo={selectTo}
      selectedFrom={selectedFrom}
      selectedTo={selectedTo}
      active={active}
      index={1}
      tdItems={tdItems}
      tableBodyRows={tableBodyRows}
    />
    <TableBodyRow
      changeFormValues={changeFormValues}
      exchangeRate={exchangeRate}
      selectFrom={selectFrom}
      selectTo={selectTo}
      selectedFrom={selectedFrom}
      selectedTo={selectedTo}
      active={active}
      index={2}
      tdItems={tdItems}
      tableBodyRows={tableBodyRows}
    />
    <TableBodyRow
      changeFormValues={changeFormValues}
      exchangeRate={exchangeRate}
      selectFrom={selectFrom}
      selectTo={selectTo}
      selectedFrom={selectedFrom}
      selectedTo={selectedTo}
      active={active}
      index={3}
      tableBodyRows={tableBodyRows}
    />
    <TableBodyRow
      changeFormValues={changeFormValues}
      exchangeRate={exchangeRate}
      selectFrom={selectFrom}
      selectTo={selectTo}
      selectedFrom={selectedFrom}
      selectedTo={selectedTo}
      active={active}
      index={4}
      tdItems={tdItems}
      tableBodyRows={tableBodyRows}
    />
  </tbody>
);

export default TableBody;
